services:
  - type: web
    name: between-private-relay
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    autoDeployTrigger: commit
    numInstances: 1
    envVars:
      - key: DEVICE_REGISTRATION_KEY
        sync: false
