package com.example.privatevault.ui.theme

import androidx.compose.ui.graphics.Color

// Stable violet/indigo palette derived from the supplied light and dark chat references.
val LightPrimary = Color(0xFF555ACB)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFE1E2FF)
val LightOnPrimaryContainer = Color(0xFF151958)
val LightSecondary = Color(0xFF77558E)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFF3DAFF)
val LightOnSecondaryContainer = Color(0xFF2E123F)
val LightTertiary = Color(0xFF735573)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFFD7F7)
val LightOnTertiaryContainer = Color(0xFF2B122C)
val LightBackground = Color(0xFFFDF8FF)
val LightOnBackground = Color(0xFF1C1B22)
val LightSurface = Color(0xFFFDF8FF)
val LightOnSurface = Color(0xFF1C1B22)
val LightSurfaceVariant = Color(0xFFE5E1EC)
val LightOnSurfaceVariant = Color(0xFF47464F)
val LightOutline = Color(0xFF777680)
val LightOutlineVariant = Color(0xFFC8C5D0)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightSurfaceDim = Color(0xFFDED9E1)
val LightSurfaceBright = Color(0xFFFDF8FF)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF8F2FA)
val LightSurfaceContainer = Color(0xFFF2EDF5)
val LightSurfaceContainerHigh = Color(0xFFECE7EF)
val LightSurfaceContainerHighest = Color(0xFFE6E1E9)

val DarkPrimary = Color(0xFFBEC2FF)
val DarkOnPrimary = Color(0xFF24296F)
val DarkPrimaryContainer = Color(0xFF3C428B)
val DarkOnPrimaryContainer = Color(0xFFE1E2FF)
val DarkSecondary = Color(0xFFE1B9F6)
val DarkOnSecondary = Color(0xFF452557)
val DarkSecondaryContainer = Color(0xFF5D3C6E)
val DarkOnSecondaryContainer = Color(0xFFF3DAFF)
val DarkTertiary = Color(0xFFE2BBDD)
val DarkOnTertiary = Color(0xFF422642)
val DarkTertiaryContainer = Color(0xFF5A3C5A)
val DarkOnTertiaryContainer = Color(0xFFFFD7F7)
val DarkBackground = Color(0xFF12121A)
val DarkOnBackground = Color(0xFFE6E1E9)
val DarkSurface = Color(0xFF12121A)
val DarkOnSurface = Color(0xFFE6E1E9)
val DarkSurfaceVariant = Color(0xFF47464F)
val DarkOnSurfaceVariant = Color(0xFFC8C5D0)
val DarkOutline = Color(0xFF91909A)
val DarkOutlineVariant = Color(0xFF47464F)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkSurfaceDim = Color(0xFF12121A)
val DarkSurfaceBright = Color(0xFF393840)
val DarkSurfaceContainerLowest = Color(0xFF0D0D14)
val DarkSurfaceContainerLow = Color(0xFF1B1B23)
val DarkSurfaceContainer = Color(0xFF1F1F27)
val DarkSurfaceContainerHigh = Color(0xFF2A2931)
val DarkSurfaceContainerHighest = Color(0xFF35343C)
